[NODE]
# The file directory where the node can store its persistent data
data_dir = "\Users\Jeremy\OneDrive\Desktop\metanode\node\here"
# How many ledger objects per ledger_data request to fetch
snapshot_chunk_size = 64000
# How many ledgers to fetch in advance before writing them to the database
stream_queue_size = 100
# Any ledgers before this sequence will be ignored
# For full-history livenet, this value should be 32570, beause the first 32569 ledgers were lost
backfill_to_ledger = 32570


[[SOURCE.XRPLS]]
# A public websocket endpoint provided by a rippled or clio node
# The node will pull all relevant ledger data from there
url = "wss://xrplcluster.com"
connections = 2

[[SOURCE.XRPLS]]
url = "wss://s2.ripple.com"
connections = 2

[[SOURCE.XRPLS]]
url = "wss://s1.ripple.com"



[[SOURCE.TOKENLISTS]]
# Tokenlists are manually published lists containing token metadata according to XLS-26
# https://github.com/XRPLF/XRPL-Standards/discussions/71
# You can add as many as you want
# The id field is used for ranking. Read below at "source_ranking"
# The trust_level field defines the maximum possible trust level the list can set for any token
id = "metadata"
url = "xdtxrp.io/.well-known/xrp-ledger.toml"
fetch_interval = 30
trust_level = 3


[SOURCE.ISSUERDOMAIN]
# All issuing accounts with the Domain field set are being automatically crawled for
# DOMAIN/.well-known/xrp-ledger.toml. If the issuer published metadata about their token
# according to XLS-26, the data will be copied and presented by the server.
concurrency = 3
connection_timeout = 10
fetch_interval = 600


[SOURCE.XRPLF]
# The XRPL Foundation provides token self-assessments made by issuers
# The node fetches wether a token issuer has completed it
fetch_interval = 60


[SOURCE.XRPSCAN]
# xrpscan.com provides usernames, social media links and verifications of XRPL accounts.
# https://docs.xrpscan.com/api-doc.html#get-names
fetch_interval = 600


[SOURCE.GRAVATAR]
# gravatar.com provides avatar images for XRPL accounts that are linked via the on-chain Account "EmailHash" field.
fetch_interval = 43200
max_requests_per_minute = 60


# [SOURCE.XUMM]
# xumm.app provides a list of curated assets, KYC status and avatar images.
# It is required to obtain an API key to use this service.
# https://apps.xumm.dev

 api_key = "af61d841-7026-4e53-a3b8-67c2557178de"
 api_secret = "ff189964-91c8-4228-a8b2-0c287c62641f"
 fetch_interval_assets = 60
 fetch_interval_kyc = 43200
 fetch_interval_avatar = 43200
 max_requests_per_minute = 30


# [SOURCE.BITHOMP]
# bithomp.com provides icons, usernames, website and social media links for XRPL accounts.
# It is required to obtain an API key for this service.
# https://bithomp.com/developer
#
 refresh_interval = 600
 api_key = "cd4d0592-af80-4075-b69e-1f6f69d0b0df"


# [SOURCE.TWITTER]
# twitter.com can provide icons, display names, website links and descriptions for both XRPL accounts and tokens.
# It is required to obtain an API key for this service.
# https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api
#
 bearer_token = "AAAAAAAAAAAAAAAAAAAAAPy2uwEAAAAAYE6o461%2BvUfW7TXU8%2Fob19meBr4%3Dg1kg8X3GRy3l4FTCUhsZxBKczdvuF99rbvHkas1H5274kicPSW"
 fetch_interval = 3600
 max_requests_per_minute = 60



[API]
# The server listens on the specified port for incoming HTTP (REST + WebSocket) connections.
port = 4080

# Set this to the URL under which your node is reachable. 
# This is required for the API to correctly return the URLs of locally cached media files, such as token icons.
 public_url = "https://xdtxrp.io"

# Multiple sources can give conflicting data for the same field. This array defines who's data has precedence,
# from highest to lowest. Example for the values below: 
# if XUMM, Bithomp and Twitter all define an icon for a token, the one from XUMM will be used.
source_ranking = [
	'ledger',			# on-chain values, such as the "Domain" field
	'tokenlist',		# .toml files published by trusted entities
	'issuer/domain',	# .toml files published by the token issuer, linked via the "Domain" field
	'xumm/curated',		# names and icons, manually set by Xumm
	'xumm/avatar',		# user defined icons from Xumm
	'gravatar',
	'bithomp',
	'xrpscan',
	'twitter'
]